### ISSUE TITLE
Does not run with Django < 1.2

### ISSUE THREAD

**Issue by passy** [weluse/django-nose-selenium#4]
```
Traceback (most recent call last):
File "/usr/lib/pymodules/python2.6/django/test/testcases.py", line 242, in __call__
    self._pre_setup()
File "/usr/lib/pymodules/python2.6/django/test/testcases.py", line 217, in _pre_setup
    self._fixture_setup()
File "/usr/lib/pymodules/python2.6/django/test/testcases.py", line 439, in _fixture_setup
    if not settings.DATABASE_SUPPORTS_TRANSACTIONS:
File "/usr/lib/pymodules/python2.6/django/utils/functional.py", line 273, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'DATABASE_SUPPORTS_TRANSACTIONS'
```

**Comment by piotrkilczuk** [comment]
I'm not sure if it runs even in 1.2 which I'm stuck with in one project (it just doesn't seem to start liveserver)
