### ISSUE TITLE
Test class has no attribute _exc_info

### ISSUE THREAD

**Issue by keokilee** [weluse/django-nose-selenium#5]
I've been getting this exception on Django 1.2.4 and Python 2.7.

<pre>
Traceback (most recent call last):
  File "/Users/gelee/Envs/pinax/lib/python2.7/site-packages/nose/case.py", line 133, in run
    self.runTest(result)
  File "/Users/gelee/Envs/pinax/lib/python2.7/site-packages/nose/case.py", line 151, in runTest
    test(result)
  File "/Users/gelee/Envs/pinax/lib/python2.7/site-packages/django/test/testcases.py", line 264, in __call__
    super(TransactionTestCase, self).__call__(result)
  File "/usr/local/Cellar/python/2.7.1/lib/python2.7/unittest/case.py", line 376, in __call__
    return self.run(*args, **kwds)
  File "/usr/local/Cellar/python/2.7.1/lib/python2.7/unittest/case.py", line 295, in run
    result.startTest(self)
  File "/Users/gelee/Envs/pinax/lib/python2.7/site-packages/nose/proxy.py", line 161, in startTest
    self.plugins.startTest(self.test)
  File "/Users/gelee/Envs/pinax/lib/python2.7/site-packages/nose/plugins/manager.py", line 94, in __call__
    return self.call(*arg, **kw)
  File "/Users/gelee/Envs/pinax/lib/python2.7/site-packages/nose/plugins/manager.py", line 162, in simple
    result = meth(*arg, **kw)
  File "/Users/gelee/Envs/pinax/lib/python2.7/site-packages/noseselenium/plugins.py", line 92, in startTest
    self._inject_selenium(test)
  File "/Users/gelee/Envs/pinax/lib/python2.7/site-packages/noseselenium/plugins.py", line 139, in _inject_selenium
    test.test._exc_info.im_self.selenium = sel
AttributeError: 'test_setup_wizard' object has no attribute '_exc_info'
</pre>

I was able to fix it by changing it from `test.test._exc_info.im_self.selenium` to `test.test.selenium`, but I'm not skilled enough in Python to know what _exc_info is for.  Any ideas?

**Comment by passy** [comment]
I figure this is caused by the 2.7 release that I did not run any tests with yet. However, could you provide the failing test case or a minimal failing version of it?

**Comment by keokilee** [comment]
Thanks for the reply!  Here's a sample test that I put together.

<pre>
import time, re
from noseselenium.cases import SeleniumTestCaseMixin
from django.test import TestCase

class sample_test(TestCase, SeleniumTestCaseMixin):
    def setUp(self):
        self.verificationErrors = []
    
    def test_sample_test(self):
        sel = self.selenium
        sel.open("/")
        try: self.failUnless(sel.is_text_present("Welcome"))
        except AssertionError, e: self.verificationErrors.append(str(e))
    
    def tearDown(self):
        self.assertEqual([], self.verificationErrors)
</pre>


This was invoked using `./manage.py test sample_test --with-selenium --with-cherrypyliveserver` using nose 1.0.0, django-nose 0.1, CherryPy 3.2, and this plugin straight from the repository.

**Comment by husio** [comment]
I've got the same error when running with python 2.7. It seems that only 2.6 and older `unittest.TestCase` classes provides `_exc_info` method. 

http://hg.python.org/cpython/file/b9a95ce2692c/Lib/unittest.py#l308

Quick solution will be adding this method to your test case (works for me) but I guess it's usage should be removed from the host library.

**Comment by passy** [comment]
Hi,

thanks for your investigation. Relying on a private interface was a bad idea in the first place. I pushed a simple patch that should fix the issue. Can you confirm it works?
